project:
  type: book

book:
  title: "Test libro"
  author: "Adrián Cidre"
  date: "2024/05/28"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



